ALTER TABLE pacientes 
ADD COLUMN IF NOT EXISTS acompanante TEXT,
ADD COLUMN IF NOT EXISTS padre TEXT,
ADD COLUMN IF NOT EXISTS madre TEXT,
ADD COLUMN IF NOT EXISTS contactos JSONB DEFAULT '{}'::jsonb;
